them hoan thien user management
tnowad/warehouse-pro pull request #25
Opened 2024-11-06 03:54 UTC by Vhuu08092004

2024-11-06 05:22 UTC, tnowad requested changes

2024-11-06 05:22 UTC, tnowad commented on client/src/lib/schemas/permission.schema.ts
> +  "REGISTER", // Đăng kí gì ?
It's placeholder for permission, please don't add comment here to avoid conflict

2024-11-06 05:22 UTC, tnowad commented on server/src/main/java/com/warehousepro/controller/AuthenticationController.java
> +
Remove empty space

2024-11-06 05:22 UTC, tnowad commented on server/src/main/java/com/warehousepro/controller/PermissionController.java
> +  @PutMapping("/assignRoleToPermission/{per_id}/{role_id}")
Don't use abbr `per_id`, use `permission_name` or `permissionName`

2024-11-06 05:22 UTC, tnowad commented on server/src/main/java/com/warehousepro/controller/ProductController.java
> +
Why?

2024-11-06 05:22 UTC, tnowad commented on server/src/main/java/com/warehousepro/controller/UserController.java
> +  @GetMapping("/viewUserPermission/{user_id}")
`/users/{user_id}/roles/permisssions`

2024-11-06 05:22 UTC, tnowad commented on server/src/main/java/com/warehousepro/controller/UserController.java
> +  @GetMapping("/viewUserRole/{user_id}")
`users/{user_id}/roles`

2024-11-06 05:22 UTC, tnowad commented on server/src/main/java/com/warehousepro/dto/response/role/RoleRespone.java
> +public class RoleRespone {
You're missing `id`

2024-11-06 05:22 UTC, tnowad commented on server/src/main/java/com/warehousepro/service/PermissionService.java
> +  public Permission assignRoleToPermission(String perId, String roleId) {
Don't use abbreviation

2024-11-06 05:22 UTC, tnowad commented on server/src/main/java/com/warehousepro/service/RoleService.java
> +//    if(request.getName() == null || request.getName().isEmpty()){
Remove comments

2024-11-06 05:22 UTC, tnowad commented on server/src/main/java/com/warehousepro/service/RoleService.java
> +//import com.warehousepro.dto.request.auth.RoleRequest;
Remove comments

2024-11-06 05:22 UTC, tnowad commented on server/src/main/java/com/warehousepro/service/UserService.java
> +  RoleRepository roleRepository;
Wrong service, `RoleRepository` only import in `RoleService`, `PermissionRepository` only import in `PermissisonService`

2024-11-07 01:15 UTC, Vhuu08092004 commented on server/src/main/java/com/warehousepro/controller/ProductController.java
> +
create new product

2024-11-07 01:19 UTC, Vhuu08092004 commented on server/src/main/java/com/warehousepro/dto/response/role/RoleRespone.java
> +public class RoleRespone {
My id is name

2024-11-07 04:21 UTC, merged