feat: Create Warehouse Functionality
tnowad/warehouse-pro pull request #6
Opened 2024-10-08 18:25 UTC by lmv2004

2024-10-08 21:04 UTC, lmv2004 commented
anh ơi review giúp em với

2024-10-09 09:01 UTC, tnowad requested changes

2024-10-09 09:01 UTC, tnowad commented on server/src/main/java/com/warehousepro/controller/WareHouseController.java
> +    public List<WareHouseResponseDto> getAllWarehouse() {
It’s not ideal to return a list of `WarehouseResponseDto` directly. Instead, consider creating a paginated response DTO as outlined in this example:  
[Pagination Example - REST API Design Guide](https://github.com/NationalBankBelgium/REST-API-Design-Guide/wiki/Pagination-Example).

This approach improves scalability and ensures consistency with API best practices.

2024-10-09 09:01 UTC, tnowad commented on server/src/main/java/com/warehousepro/controller/WareHouseController.java
> +    public String deleteWarehouse(@PathVariable("id") int id) {
> 204 No Content - Response to a successful request that won't be returning a body (like a DELETE request)

2024-10-09 09:01 UTC, tnowad commented on server/src/main/java/com/warehousepro/service/WareHouseService.java
> +    public List<Warehouse> getAllWareHouse() {
It should support pagination, sort, and filter

2024-10-09 09:01 UTC, tnowad commented on server/src/main/java/com/warehousepro/service/WareHouseService.java
> +    public Warehouse getWareHouse(int warehouse_id) {
Please follow the java coding rule, don't use `snake_case` in here

2024-10-09 09:37 UTC, tnowad commented on server/src/main/java/com/warehousepro/service/WareHouseService.java
> +    public List<Warehouse> getAllWareHouse() {
https://docs.spring.io/spring-data/jpa/reference/jpa/specifications.html

2024-10-10 07:27 UTC, tnowad approved these changes

2024-10-10 07:27 UTC, merged